services:
  base:
    build:
      dockerfile: docker/base/Dockerfile
      context: .
    command: ["true"]
  metagraph:
    build:
      dockerfile: docker/metagraph/Dockerfile
      context: .
    depends_on:
      - redis
      - base
  miner:
    build:
      dockerfile: docker/miner/Dockerfile
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - metagraph
      - base
  validator:
    build:
      dockerfile: docker/validator/Dockerfile
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - metagraph
      - base
  redis:
    image: redis/redis-stack:latest
    ports:
    - "6379:6379"