services:
  miner:
    build:
      dockerfile: docker/miner/Dockerfile
      context: .
    ports:
      - "8001:8001"
  validator:
    build:
      dockerfile: docker/validator/Dockerfile
      context: .
    ports:
      - "8000:8000"
  metagraph:
    build:
      dockerfile: docker/metagraph/Dockerfile
      context: .
  redis:
    image: redis/redis-stack:latest
    ports:
    - "6379:6379"